apiVersion: v1
kind: Pod
metadata:
  name: mm-service-pod
  labels:
    app: mm-service-pod
spec:
  containers:
    - name: middleware
      image: binciluo/middleware:latest
      ports:
        - containerPort: 8080
    - name: gradio-web
      image: binciluo/gradio_web:latest
      command: ["/bin/sh", "-c"]
      args:
        - "export MIDDLEWARE_ENV=k8s && export GR_PORT=27777 && python webui.py"
      ports:
        - containerPort: 27777
  dnsPolicy: Default  # 默认情况下，Pod可以访问外部网络

---

apiVersion: v1
kind: Service
metadata:
  name: mm-service
spec:
  type: NodePort
  ports:    
    - port: 27777
      targetPort: 27777
      nodePort: 30004
  selector:
    app: mm-service-pod