apiVersion: v1
kind: Service
metadata:
  name: gradio-web-service
spec:
  type: NodePort
  ports:    
    - port: 27777
      targetPort: 27777
      nodePort: 30004
  selector:
    app: my-service-pod
  
