name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image gradio
      run: docker build . --file docker/gradio_web/Dockerfile --tag binciluo/gradio_web:$(date +%s)
    - name: Build the Docker image middleware
      run: docker build . --file docker/middleware/Dockerfile --tag binciluo/middleware:$(date +%s)
