name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build the Docker image gradio
      run: docker build . --file docker/gradio_web/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/gradio_web:latest
    - name: Build the Docker image middleware
      run: docker build . --file docker/middleware/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/middleware:latest
    - name: Docker image push gradio_web
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gradio_web:latest
    - name: Docker image push middleware
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/middleware:latest
      
