name: Docker Image CI for ARM64

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build the Docker image gradio
      run: docker build . --no-cache --file docker/gradio_web/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/gradio_web:arm_latest
    
    - name: Build the Docker image middleware
      run: docker build . --no-cache --file docker/middleware/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/middleware:arm_latest
    
    - name: Docker image push gradio_web
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/gradio_web:arm_latest
    
    - name: Docker image push middleware
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/middleware:arm_latest
